# Generated by Django 5.2.2 on 2025-06-05 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encomiendas', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomiendas', to='rutas.salida'),
        ),
    ]
