# Generated by Django 5.2.2 on 2025-06-05 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('capacidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'Mantenimiento'), ('inactivo', 'Inactivo')], default='activo', max_length=15)),
                ('conductor', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehiculos',
                'ordering': ['placa'],
            },
        ),
    ]
