# Generated by Django 5.2.2 on 2025-06-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('asiento', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('pagado', 'Pagado'), ('abordado', 'Abordado'), ('no_show', 'No Show')], default='reservado', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pasajes',
                'ordering': ['asiento'],
            },
        ),
    ]
