# Generated by Django 5.2.2 on 2025-06-05 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pasajes', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasaje',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasajes', to='rutas.salida'),
        ),
        migrations.AlterUniqueTogether(
            name='pasaje',
            unique_together={('salida', 'asiento')},
        ),
    ]
